import type { Metadata } from "next";
import { Exo_2, Lato } from "next/font/google"; // Change to Exo 2 and Lato imports
import "./globals.css";
import Navbar from "./(components)/navbar/page";
import Footer from "./(components)/footer/page";

// Define the font with variables and weights
const exo2 = Exo_2({
  variable: "--font-exo", // Custom variable for Exo 2 font
  weight: ["400", "600"], // Add the weights you want to use (normal and bold)
  subsets: ["latin"], // Subset for Latin characters
});

const lato = Lato({
  variable: "--font-lato", // Custom variable for Lato font
  weight: ["300", "400", "700"], // Add weights for Lato
  subsets: ["latin"], // Subset for Latin characters
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo2.variable} ${lato.variable} antialiased`} // Use the font variables in your body class
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
